# Name: roger kewin samson
# Hawk ID : A20563057
# Course : CS512
# semester : 4th semester

In [60]:
import numpy as np


In [61]:
p = np.array([[2], [-1], [4]])
q = np.array([[0], [3], [5]])
r = np.array([[1], [-2], [2]])

# 1. 3p + 2q


In [62]:
result_1 = 3 * p + 2 * q
print( result_1)

[[ 6]
 [ 3]
 [22]]


# 2. Unit vector in the direction of p


In [63]:
p_magnitude = np.linalg.norm(p)
p_hat = p / p_magnitude
print(p_hat)

[[ 0.43643578]
 [-0.21821789]
 [ 0.87287156]]


# 3. Magnitude of p and angle with the positive y-axis


In [64]:
p_magnitude = np.linalg.norm(p)
angle_with_y_axis = np.degrees(np.arccos(p[1] / p_magnitude))
print(p_magnitude)
print(angle_with_y_axis)


4.58257569495584
[102.60438265]


# 4. Direction cosines of p


In [65]:
direction_cosines = p / p_magnitude
print( direction_cosines)

[[ 0.43643578]
 [-0.21821789]
 [ 0.87287156]]


# 5. Angle between p and q


In [66]:
dot_product_pq = np.dot(p.T, q)[0, 0]  # Transpose p to align for dot product
angle_pq = np.degrees(np.arccos(dot_product_pq / (np.linalg.norm(p) * np.linalg.norm(q))))
print( angle_pq)


50.490287713806076


# 6. p · q and q · p (dot products)


In [67]:
dot_pq = np.dot(p.T, q)[0, 0]
dot_qp = np.dot(q.T, p)[0, 0]
print( dot_pq)
print( dot_qp)


17
17


# 7. p · q using the angle between p and q


In [68]:
dot_from_angle = np.linalg.norm(p) * np.linalg.norm(q) * np.cos(np.radians(angle_pq))
print( dot_from_angle)

17.0


# 8. Scalar projection of q onto p-hat


In [69]:
scalar_proj = np.dot(q.T, p_hat)[0, 0]
print( scalar_proj)

3.709704134011871


# 9. A vector that is perpendicular to p


In [70]:
perpendicular_vector = np.cross(p.flatten(), q.flatten())
print( perpendicular_vector)

[-17 -10   6]


# 10. p × q and q × p

In [71]:
cross_pq = np.cross(p.flatten(), q.flatten())
cross_qp = np.cross(q.flatten(), p.flatten())
print( cross_pq)
print( cross_qp)

[-17 -10   6]
[17 10 -6]


# 11. A vector that is perpendicular to both p and q


In [72]:
perpendicular_to_pq = np.cross(p.flatten(), q.flatten())
print( perpendicular_to_pq)

[-17 -10   6]


# 12. Linear dependency between p, q, and r


In [73]:
matrix_pqr = np.column_stack((p, q, r))
determinant_pqr = np.linalg.det(matrix_pqr)
linear_dependency = np.isclose(determinant_pqr, 0)
print(f"Determinant: {determinant_pqr}")
print(f"Linear Dependence: {linear_dependency}")

Determinant: 15.0
Linear Dependence: False


# 13. pᵀq and pqᵀ

In [74]:
pTq = np.dot(p.T, q)
pqT = np.dot(p, q.T)
print( pTq)
print( pqT)

[[17]]
[[ 0  6 10]
 [ 0 -3 -5]
 [ 0 12 20]]
