# Name: roger kewin samson
# Hawk ID : A20563057
# Course : CS512
# semester : 4th semester

In [19]:
import numpy as np

In [20]:
X = np.array([[2, 1, 0], [-1, 3, 4], [3, 2, -2]])
Y = np.array([[4, -1, 2], [3, 0, -3], [1, 2, 1]])
Z = np.array([[2, 0, -1], [1, 4, 5], [3, 1, 2]])
s = np.array([[-1], [4], [0]])


# 1. X + 2Y


In [21]:
result_1 = X + 2 * Y
print("X + 2Y:\n", result_1)

X + 2Y:
 [[10 -1  4]
 [ 5  3 -2]
 [ 5  6  0]]


# 2. XY and YX

In [22]:
result_2_XY = np.dot(X, Y)
result_2_YX = np.dot(Y, X)
print("XY:\n", result_2_XY)
print("   YX:\n", result_2_YX)

XY:
 [[11 -2  1]
 [ 9  9 -7]
 [16 -7 -2]]
   YX:
 [[15  5 -8]
 [-3 -3  6]
 [ 3  9  6]]


# 3. (XY)^T and Y^T X^T

In [23]:
result_3_XY_T = result_2_XY.T
result_3_YT_XT = np.dot(Y.T, X.T)
print("(XY)^T:\n", result_3_XY_T)
print("   Y^T X^T:\n", result_3_YT_XT)

(XY)^T:
 [[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]
   Y^T X^T:
 [[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]


# 4. Determinants |X| and |Z|

In [24]:
det_X = np.linalg.det(X)
det_Z = np.linalg.det(Z)
print(" Determinant of X:", det_X)
print("   Determinant of Z:", det_Z)

 Determinant of X: -17.999999999999996
   Determinant of Z: 17.0


# 5. Finding the matrix with orthogonal row vectors

In [25]:
def is_orthogonal(matrix):
    row_dot_products = np.dot(matrix, matrix.T)
    identity = np.eye(matrix.shape[0])
    return np.allclose(row_dot_products, identity * np.linalg.norm(matrix, axis=1)**2)

orthogonal_matrix = "None"
if is_orthogonal(X):
    orthogonal_matrix = "X"
elif is_orthogonal(Y):
    orthogonal_matrix = "Y"
elif is_orthogonal(Z):
    orthogonal_matrix = "Z"

print("The matrix with orthogonal row vectors:", orthogonal_matrix)

The matrix with orthogonal row vectors: None


# 6. X⁻¹ and Y⁻¹

In [26]:
try:
    X_inv = np.linalg.inv(X)
    print(" X⁻¹:\n", X_inv)
except np.linalg.LinAlgError:
    print(" X⁻¹ does not exist (singular matrix).")

try:
    Y_inv = np.linalg.inv(Y)
    print("   Y⁻¹:\n", Y_inv)
except np.linalg.LinAlgError:
    print("   Y⁻¹ does not exist (singular matrix).")


 X⁻¹:
 [[ 0.77777778 -0.11111111 -0.22222222]
 [-0.55555556  0.22222222  0.44444444]
 [ 0.61111111  0.05555556 -0.38888889]]
   Y⁻¹:
 [[ 0.14285714  0.11904762  0.07142857]
 [-0.14285714  0.04761905  0.42857143]
 [ 0.14285714 -0.21428571  0.07142857]]


# 7. Z⁻¹

In [27]:
try:
    Z_inv = np.linalg.inv(Z)
    print("Z⁻¹:\n", Z_inv)
except np.linalg.LinAlgError:
    print(" Z⁻¹ does not exist (singular matrix).")


Z⁻¹:
 [[ 0.17647059 -0.05882353  0.23529412]
 [ 0.76470588  0.41176471 -0.64705882]
 [-0.64705882 -0.11764706  0.47058824]]


# 8. Product Xs

In [13]:
result_8 = np.dot(X, s)
print(result_8)

8. Xs:
 [[ 2]
 [13]
 [ 5]]


# 9. Scalar projection of rows of X onto s (normalized)

In [28]:
s_norm = s / np.linalg.norm(s)
scalar_proj = np.dot(X, s_norm)
print(scalar_proj)

[[0.48507125]
 [3.15296313]
 [1.21267813]]


# 10. Vector projection of rows of X onto s (normalized)

In [29]:
vector_proj = np.dot(s_norm, s_norm.T) @ X.T
print(vector_proj.T)

[[-0.11764706  0.47058824  0.        ]
 [-0.76470588  3.05882353  0.        ]
 [-0.29411765  1.17647059  0.        ]]


# 11. Linear combination of X columns using s elements

In [30]:
linear_combination = X @ s
print(linear_combination)


[[ 2]
 [13]
 [ 5]]


# 12. Solution for Yt = s

In [31]:
try:
    t_Y = np.linalg.solve(Y, s)
    print(t_Y)
except np.linalg.LinAlgError:
    print(" No unique solution for Yt = s.")

[[ 0.33333333]
 [ 0.33333333]
 [-1.        ]]


# 13. Solution for Zt = s and the reason


In [32]:
try:
    t_Z = np.linalg.solve(Z, s)
    print(" Solution for Zt = s:\n", t_Z)
except np.linalg.LinAlgError:
    print(" No unique solution for Zt = s because Z is singular.")

 Solution for Zt = s:
 [[-0.41176471]
 [ 0.88235294]
 [ 0.17647059]]
